name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *' # 每天凌晨运行一次（UTC 时间）
  workflow_dispatch:    # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork
        uses: actions/checkout@v3
        with:
          repository: iJonSo/ollama
          ref: main # 确保和你的默认分支一致

      - name: Add upstream remote
        run: git remote add upstream https://github.com/ollama/ollama.git || true

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git merge upstream/main --allow-unrelated-histories || true

      - name: Push changes to your fork
        run: git push origin main
